name: API Tests Daily

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.function }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - function: active_inout
            spec: tests/base_tests.py::test_active_inout
          - function: cities_list
            spec: tests/base_tests.py::test_cities_list
          - function: categories_list
            spec: tests/base_tests.py::test_categories_list
          - function: products_list
            spec: tests/base_tests.py::test_products_list
          - function: download_image
            spec: tests/base_tests.py::test_download_image
          - function: set_debug
            spec: tests/base_tests.py::test_set_debug
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt camoufox

      - name: Install Playwright dependencies
        run: playwright install-deps

      - name: Install Playwright browsers
        run: playwright install

      - name: Run ${{ matrix.function }}
        run: pytest ${{ matrix.spec }} --maxfail=3
