name: API Tests Daily

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  build_env:
    name: Build test environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt camoufox
          playwright install-deps
          playwright install

      - name: Upload environment
        uses: actions/upload-artifact@v2
        with:
          name: venv
          path: venv

  test_active_inout:
    name: Test active_inout
    needs: build_env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download environment
        uses: actions/download-artifact@v2
        with:
          name: venv

      - name: Activate and test
        run: |
          source venv/bin/activate
          venv/bin/python -m pytest tests/base_tests.py::test_active_inout --maxfail=3

  test_cities_list:
    name: Test cities_list
    needs: build_env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download environment
        uses: actions/download-artifact@v2
        with:
          name: venv

      - name: Activate and test
        run: |
          source venv/bin/activate
          venv/bin/python -m pytest tests/base_tests.py::test_cities_list --maxfail=3

  test_categories_list:
    name: Test categories_list
    needs: build_env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download environment
        uses: actions/download-artifact@v2
        with:
          name: venv

      - name: Activate and test
        run: |
          source venv/bin/activate
          venv/bin/python -m pytest tests/base_tests.py::test_categories_list --maxfail=3

  test_products_list:
    name: Test products_list
    needs: build_env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download environment
        uses: actions/download-artifact@v2
        with:
          name: venv

      - name: Activate and test
        run: |
          source venv/bin/activate
          venv/bin/python -m pytest tests/base_tests.py::test_products_list --maxfail=3

  test_download_image:
    name: Test download_image
    needs: build_env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download environment
        uses: actions/download-artifact@v2
        with:
          name: venv

      - name: Activate and test
        run: |
          source venv/bin/activate
          venv/bin/python -m pytest tests/base_tests.py::test_download_image --maxfail=3

  test_set_debug:
    name: Test set_debug
    needs: build_env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download environment
        uses: actions/download-artifact@v2
        with:
          name: venv

      - name: Activate and test
        run: |
          source venv/bin/activate
          venv/bin/python -m pytest tests/base_tests.py::test_set_debug --maxfail=3
